### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by dwightjack** [posabsolute/inker#1]
Hi,

I've spotted a typo on the documentation: at line 342 the link to grunt-nodemailer returns a 404.

Apart from that, great project. I was working as well on a similar project, but I'm finding it a bit hard to maintain it, so i think that maybe I'd try to converge on this one :)

**Comment by posabsolute** [comment]
Hey @dwightjack updated the link to your repo, 

yeah I often got the same issue with my projects ;), if you ever want to converge I will give you admin access on the repo.

a+
